import{W,H,NODE,MEMORIES,distance,random,createGame,pulse,extract,step,readSave,bank}from'./engine.mjs';
const $=id=>document.getElementById(id),canvas=$('world'),ctx=canvas.getContext('2d');
let storage;try{storage=localStorage;}catch{storage={getItem:()=>null,setItem:()=>{throw Error('unavailable');}};}
let save=readSave(storage),g=createGame(404),mode='intro',last=0,lastMessage=0,toastUntil=0,sound=false,audio,cam={x:450,y:900},keys=new Set(),held=new Map(),archivePaused=false;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,rng=random(404);
const grass=Array.from({length:4500},()=>({x:rng()*W,y:rng()*H,h:2+rng()*8,v:rng()}));
const trees=Array.from({length:80},()=>({x:rng()*W,y:70+rng()*(H-160),r:10+rng()*15})).filter(t=>distance(t,NODE)>125);
function tone(freq,duration=.15,type='sine',vol=.035){if(!sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),v=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.6,audio.currentTime+duration);v.gain.setValueAtTime(vol,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{sound=false;$('sound').textContent='Sonido no disponible';}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');toastUntil=performance.now()+4500;}
function updateSave(){ $('archiveCount').textContent=`${String(save.known.length).padStart(2,'0')} / 12 ↗`;$('best').textContent=String(save.best).padStart(4,'0');}
function start(){g=createGame(Date.now(),save.known);mode='playing';lastMessage=0;keys.clear();held.clear();$('overlay').hidden=true;$('pause').disabled=false;$('pause').textContent='Pausar ⏸';tone(440);canvas.focus();}
function doPulse(){if(mode==='playing'&&pulse(g))tone(260,.7,'sine',.06);}
function doExtract(){if(mode!=='playing')return;if(extract(g))finish();else toast(g.cargo.length?'Acercate al nodo de salida al sur.':'Primero recuperá una memoria.');}
function pauseGame(){if(!['playing','paused'].includes(mode))return;mode=mode==='playing'?'paused':'playing';keys.clear();held.clear();$('pause').textContent=mode==='paused'?'Continuar ▶':'Pausar ⏸';$('overlay').hidden=mode==='playing';if(mode==='paused'){document.querySelector('h1').innerHTML='RUTA<br><em>404</em><span>PAUSA</span>';$('introText').textContent='La ruta espera. Tu tiempo y tu señal están detenidos.';$('instructions').hidden=true;$('start').innerHTML='Continuar <span>↗</span>';$('start').focus();}else canvas.focus();}
function finish(){mode=g.phase;keys.clear();held.clear();$('overlay').hidden=false;$('pause').disabled=true;$('instructions').hidden=false;const won=mode==='won';document.querySelector('h1').innerHTML=won?'SEÑAL<br><em>VIVA</em>':'SIN<br><em>SEÑAL</em>';$('introText').textContent=won?`${g.cargo.length} memorias llegaron al archivo. ${g.score} puntos. La ruta todavía tiene algo que decir.`:g.message;
 const instructions=$('instructions');instructions.replaceChildren();if(won){save=bank(save,g);let persisted=true;try{storage.setItem('austral-ruta404-v1',JSON.stringify(save));}catch{persisted=false;}for(const id of g.cargo){const p=document.createElement('p');p.textContent='◇ '+MEMORIES[id][0];instructions.append(p);}updateSave();if(!persisted)toast('El navegador no permite guardar. El archivo durará esta sesión.');tone(660,.6);}else{const p=document.createElement('p');p.textContent='El archivo anterior sigue intacto. Probá una extracción corta antes de internarte más.';instructions.append(p);tone(95,.6,'triangle');}$('start').innerHTML='Volver a la ruta <span>↗</span>';$('start').focus();}
$('start').onclick=()=>mode==='paused'?pauseGame():start();$('pulse').onclick=doPulse;$('extract').onclick=doExtract;$('touchPulse').onclick=doPulse;$('touchExtract').onclick=doExtract;$('pause').onclick=pauseGame;
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=`Sonido: ${sound?'encendido':'apagado'}`;$('sound').setAttribute('aria-pressed',String(sound));tone(440);};
$('archiveButton').onclick=()=>{archivePaused=mode==='playing';if(archivePaused)pauseGame();const box=$('archiveEntries');box.replaceChildren();MEMORIES.forEach(([title,text],id)=>{const a=document.createElement('article'),h=document.createElement('h3'),p=document.createElement('p');h.textContent=`${String(id+1).padStart(2,'0')} / ${save.known.includes(id)?title:'Memoria sin recuperar'}`;p.textContent=save.known.includes(id)?text:'Señal pendiente de extracción.';a.append(h,p);box.append(a);});$('archive').showModal();};
$('closeArchive').onclick=()=>$('archive').close();$('archive').addEventListener('close',()=>{if(archivePaused&&mode==='paused')pauseGame();archivePaused=false;});
const controlKeys=['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d',' ','e','escape'];
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if($('archive').open)return;if(!controlKeys.includes(key))return;if(e.target instanceof HTMLButtonElement&&key===' ')return;e.preventDefault();if(e.repeat)return;keys.add(key);if(key===' ')doPulse();if(key==='e')doExtract();if(key==='escape')pauseGame();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
document.querySelectorAll('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held.set(e.pointerId,b.dataset.move);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,e=>held.delete(e.pointerId));});
window.addEventListener('blur',()=>{keys.clear();held.clear();if(mode==='playing')pauseGame();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pauseGame();});
function input(){const values=[...held.values()];return{x:Number(keys.has('d')||keys.has('arrowright')||values.includes('right'))-Number(keys.has('a')||keys.has('arrowleft')||values.includes('left')),y:Number(keys.has('s')||keys.has('arrowdown')||values.includes('down'))-Number(keys.has('w')||keys.has('arrowup')||values.includes('up'))};}
function diamond(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(x,y-r);ctx.lineTo(x+r,y);ctx.lineTo(x,y+r);ctx.lineTo(x-r,y);ctx.fill();}
function circle(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function glow(x,y,r,color){const grad=ctx.createRadialGradient(x,y,0,x,y,r);grad.addColorStop(0,color);grad.addColorStop(1,'transparent');ctx.fillStyle=grad;ctx.fillRect(x-r,y-r,r*2,r*2);}
function auri(x,y,t){const bob=reduced?0:Math.sin(t*4)*2;ctx.save();ctx.translate(Math.round(x),Math.round(y+bob));ctx.fillStyle='#07120f';ctx.fillRect(-15,15,31,6);ctx.strokeStyle='#879fa3';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(10,3);ctx.lineTo(20,0);ctx.lineTo(26,-9);ctx.lineTo(32,-12);ctx.stroke();ctx.fillStyle='#a9bec1';ctx.fillRect(-11,-3,23,16);ctx.fillStyle='#748c93';ctx.fillRect(-12,8,6,8);ctx.fillRect(7,8,5,8);ctx.fillStyle='#bcced0';ctx.fillRect(-13,-16,21,18);ctx.fillRect(-14,-23,6,12);ctx.fillRect(3,-23,6,12);ctx.fillStyle='#526d77';ctx.fillRect(-12,-21,2,5);ctx.fillRect(5,-21,2,5);ctx.fillStyle='#f0fff3';ctx.fillRect(-10,-10,5,3);ctx.fillRect(1,-10,5,3);ctx.fillStyle='#7da1a9';ctx.fillRect(-3,-4,3,2);ctx.fillStyle='#e9ffcf';ctx.beginPath();for(let i=0;i<6;i++){const angle=i*Math.PI/3;const dx=-3+Math.cos(angle)*4,dy=-16+Math.sin(angle)*4;i?ctx.lineTo(dx,dy):ctx.moveTo(dx,dy);}ctx.fill();ctx.restore();}
function draw(t){const vw=canvas.width,vh=canvas.height;cam.x=Math.max(0,Math.min(W-vw,g.x-vw/2));cam.y=Math.max(0,Math.min(H-vh,g.y-vh/2));ctx.fillStyle='#12281f';ctx.fillRect(0,0,vw,vh);ctx.save();ctx.translate(-Math.floor(cam.x),-Math.floor(cam.y));
 // The landscape is gameplay geometry rendered directly on canvas.
 ctx.strokeStyle='#24382a';ctx.lineWidth=94;ctx.beginPath();ctx.moveTo(900,1500);ctx.bezierCurveTo(760,1020,1270,750,750,0);ctx.stroke();ctx.strokeStyle='#34432d';ctx.lineWidth=2;ctx.setLineDash([12,40]);ctx.stroke();ctx.setLineDash([]);
 for(const p of grass){if(p.x<cam.x-10||p.x>cam.x+vw+10||p.y<cam.y||p.y>cam.y+vh+10)continue;ctx.strokeStyle=p.v>.6?'#32452c':'#203b29';ctx.lineWidth=1;const wind=reduced?0:Math.sin(t*.7+p.y*.03)*2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+wind+2,p.y-p.h);ctx.stroke();}
 for(let y=140;y<1500;y+=210){const x=1030+Math.sin(y*.007)*150;ctx.fillStyle='#0a1915';ctx.fillRect(x,y-68,7,90);ctx.fillRect(x-25,y-61,58,5);ctx.strokeStyle='#16271e';ctx.beginPath();ctx.moveTo(x-21,y-59);ctx.quadraticCurveTo(x-70,y+35,1030+Math.sin((y+210)*.007)*150-21,y+150);ctx.stroke();glow(x,y-60,20,'#b3a36217');}
 for(const tree of trees){if(distance(tree,g)<65)continue;ctx.fillStyle='#081c16';ctx.fillRect(tree.x-3,tree.y,6,tree.r+10);circle(tree.x,tree.y,tree.r,'#0b211a');circle(tree.x-7,tree.y-8,tree.r*.8,'#0e261c');}
 for(const h of g.holes){const visible=g.reveal>0||distance(h,g)<76;ctx.fillStyle=visible?'#040d0c':'#13251c';ctx.fillRect(h.x-h.r,h.y-h.r*.6,h.r*2,h.r*1.2);if(visible){ctx.strokeStyle='#89998a';ctx.setLineDash([3,7]);ctx.strokeRect(h.x-h.r-2,h.y-h.r*.6-2,h.r*2+4,h.r*1.2+4);ctx.setLineDash([]);ctx.fillStyle='#5b6b5b';ctx.fillRect(h.x-6,h.y-3,5,3);}}
 glow(NODE.x,NODE.y,140,'#c3eab22b');ctx.strokeStyle='#b8dba0';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(NODE.x,NODE.y,62,32,0,0,Math.PI*2);ctx.stroke();for(const dx of [-48,48]){ctx.fillStyle='#728c70';ctx.fillRect(NODE.x+dx-4,NODE.y-42,8,45);ctx.fillStyle='#d6edab';ctx.fillRect(NODE.x+dx-6,NODE.y-44,12,4);}ctx.textAlign='center';ctx.font='11px monospace';ctx.fillStyle='#d6edab';ctx.fillText('NODO / EXTRACCIÓN',NODE.x,NODE.y+56);
 for(const m of g.memories){if(m.collected||distance(m,g)>(g.reveal>0?650:245))continue;glow(m.x,m.y,38,'#e2b77428');diamond(m.x,m.y,7,'#efc785');diamond(m.x,m.y,3,'#fff3c2');}
 for(const l of g.lures){if(distance(l,g)>(g.reveal>0?650:245))continue;const exposed=g.reveal>0;glow(l.x,l.y,40,exposed?'#e65b503f':'#e2b77428');diamond(l.x,l.y,7,exposed?'#f07864':'#efc785');if(exposed){ctx.fillStyle='#ff9989';ctx.fillText('LUZ MALA',l.x,l.y-23);}}
 for(const tank of g.tanks){if(distance(tank,g)>520&&g.reveal<=0)continue;ctx.fillStyle='#091513';ctx.fillRect(tank.x-24,tank.y+9,48,12);ctx.fillStyle='#42534a';ctx.fillRect(tank.x-20,tank.y-9,40,24);ctx.fillStyle='#687367';ctx.fillRect(tank.x-11,tank.y-27,22,17);ctx.fillStyle='#302f26';ctx.fillRect(tank.x-18,tank.y-29,37,5);ctx.fillStyle='#df9b63';ctx.fillRect(tank.x-7,tank.y-19,4,3);ctx.fillRect(tank.x+3,tank.y-19,4,3);ctx.strokeStyle='#1d2620';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(tank.x,tank.y+22);ctx.lineTo(tank.x-15,tank.y+60);ctx.stroke();}
 if(g.pombero){const p=g.pombero;glow(p.x,p.y,75,'#ef795321');ctx.fillStyle='#08100c';ctx.beginPath();ctx.moveTo(p.x,p.y-32);ctx.lineTo(p.x+22,p.y+20);ctx.lineTo(p.x-22,p.y+20);ctx.fill();ctx.fillRect(p.x-24,p.y-26,48,6);ctx.fillStyle='#efad68';ctx.fillRect(p.x-8,p.y-12,4,3);ctx.fillRect(p.x+5,p.y-12,4,3);}
 if(g.reveal>0&&!reduced){ctx.strokeStyle=`rgba(215,241,183,${Math.max(0,1-g.pulseAge/2)*.7})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(g.x,g.y,g.pulseAge*330,0,Math.PI*2);ctx.stroke();}
 glow(g.x,g.y,100,'#d4ebc31e');if(g.invuln<=0||reduced||Math.floor(t*12)%2===0)auri(g.x,g.y,t);
 ctx.restore();const fog=ctx.createRadialGradient(g.x-cam.x,g.y-cam.y,90,g.x-cam.x,g.y-cam.y,g.reveal>0?750:430);fog.addColorStop(0,'transparent');fog.addColorStop(1,'#020b09bc');ctx.fillStyle=fog;ctx.fillRect(0,0,vw,vh);
 if(distance(g,NODE)>210){const dx=NODE.x-g.x,dy=NODE.y-g.y,angle=Math.atan2(dy,dx),cx=vw/2,cy=vh/2,r=Math.min(vw,vh)/2-56;const px=cx+Math.cos(angle)*r,py=cy+Math.sin(angle)*r;ctx.save();ctx.translate(px,py);ctx.rotate(angle);ctx.fillStyle='#d6edab';ctx.beginPath();ctx.moveTo(10,0);ctx.lineTo(-5,-6);ctx.lineTo(-5,6);ctx.fill();ctx.restore();ctx.fillStyle='#d6edab';ctx.font='10px monospace';ctx.textAlign='center';ctx.fillText('NODO',px,py+22);}
}
function hud(){const active=mode==='playing';$('health').innerHTML=`${Math.ceil(g.health)}<span>%</span>`;$('heat').innerHTML=`${Math.ceil(g.heat)}<span>%</span>`;$('healthBar').style.width=g.health+'%';$('heatBar').style.width=g.heat+'%';$('cargo').innerHTML=`${g.cargo.length} <small>/ 4</small>`;$('slots').textContent=Array.from({length:4},(_,i)=>i<g.cargo.length?'◆':'◇').join(' ');const seconds=Math.ceil(g.time);$('time').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;$('pulse').disabled=!active||g.cooldown>0;$('pulse').firstElementChild.textContent=g.cooldown>0?`◇ Recargando ${g.cooldown.toFixed(1)}s`:'◇ Emitir pulso';$('extract').disabled=!active||distance(g,NODE)>78||!g.cargo.length;$('touchPulse').disabled=!active||g.cooldown>0;$('touchExtract').disabled=$('extract').disabled;$('coordinates').textContent=`${String(Math.round(g.x)).padStart(4,'0')} : ${String(Math.round(g.y)).padStart(4,'0')}`;$('hint').textContent=g.heat>=60?'El Pombero te rastrea. Movete sin emitir pulsos.':g.cargo.length===4?'Carga completa. Seguí la flecha hacia el nodo.':distance(g,NODE)<78&&g.cargo.length?'Estás en el nodo. Extraé para guardar tus memorias.':'El nodo de salida está al sur. Seguí su señal para volver.';}
let hudClock=0;function frame(now){const dt=Math.min((now-last)/1000||0,.05);last=now;if(mode==='playing'){const hp=g.health,n=g.cargo.length;step(g,dt,input());if(g.health<hp)tone(80,.2,'sawtooth');if(g.cargo.length>n)tone(820,.25);if(g.messageId!==lastMessage){lastMessage=g.messageId;toast(g.message);}if(g.phase!=='playing')finish();}if(now>toastUntil)$('toast').classList.remove('show');draw(mode==='playing'?g.elapsed:0);hudClock+=dt;if(hudClock>.1){hud();hudClock=0;}requestAnimationFrame(frame);}
function resize(){const rect=canvas.getBoundingClientRect();canvas.width=Math.max(320,Math.round(rect.width));canvas.height=Math.max(320,Math.round(rect.height));ctx.imageSmoothingEnabled=false;}new ResizeObserver(resize).observe(canvas);resize();updateSave();hud();requestAnimationFrame(frame);
